/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screencapture;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Date;
import javax.imageio.ImageIO;
import tgui.ButtonLook;

/**
 *
 * @author DONGRE
 */
public class CaptureFrame extends javax.swing.JFrame {

    /**
     * Creates new form CaptureFrame
     */
    
    ButtonLook winBtnLook=new ButtonLook();
    ButtonLook hoverLook=new ButtonLook();
    String storage="E:\\www";
    
    public CaptureFrame() {
        initComponents();
        init();
    }
    public void init()
    {
        this.setBackground(new Color(0,0,0,0));
        int w=this.getWidth(),h=this.getHeight();
        Dimension ssize=Toolkit.getDefaultToolkit().getScreenSize();
        double ww=ssize.getWidth(),hh=ssize.getHeight();
        int lw,lh;
        lw=(int)ww-w;
        lh=(int)hh-h;
        lh-=40;
        this.setLocation(lw,lh);
        
        //setting look
        
        winBtnLook.setBackgroundColor(new Color(0,200,0,250));
        winBtnLook.setBorderWidth(2);
        winBtnLook.setBorderColor(new Color(0,200,0,255));
        winBtnLook.setFont(new java.awt.Font("Segoe UI",Font.BOLD,18));
        winBtnLook.setForegroundColor(new Color(0,200,0));
        btn.setLook(winBtnLook);
        
        hoverLook.setBackgroundColor(new Color(0,200,0,00));
        hoverLook.setBorderWidth(2);
        hoverLook.setBorderColor(new Color(0,200,0,255));
        hoverLook.setFont(new java.awt.Font("Segoe UI",Font.BOLD,18));
        hoverLook.setForegroundColor(new Color(0,0,0,200));
        btn.setOnHourLook(hoverLook);
        btn.setText("");
        
    }
    void setPath(String p)
    {
        this.storage=p;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tButton1 = new tgui.TButton();
        btn = new tgui.RoundButton();

        javax.swing.GroupLayout tButton1Layout = new javax.swing.GroupLayout(tButton1);
        tButton1.setLayout(tButton1Layout);
        tButton1Layout.setHorizontalGroup(
            tButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tButton1Layout.setVerticalGroup(
            tButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLayout = new javax.swing.GroupLayout(btn);
        btn.setLayout(btnLayout);
        btnLayout.setHorizontalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        btnLayout.setVerticalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        if(captureScreen())
        {
                
        }
    }//GEN-LAST:event_btnMouseClicked
    boolean captureScreen()
    {
        String fpath;
        String fnm;
        Date d=new Date();
        fnm=(d.getYear()+1900)+""+d.getMonth()+""+d.getDay()+"-"+d.getHours()+""+d.getMinutes()+""+d.getSeconds()+".png";
        if(!storage.endsWith("\\"))
            storage+="\\";
        fpath=storage+""+fnm;
        
        try
        {
            Robot r=new Robot();
            
            Rectangle capture = 
            new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage Image = r.createScreenCapture(capture);
            ImageIO.write(Image, "png", new File(fpath));
            
            System.out.println("Screenshot Saved to "+fpath);
            
        }catch(Exception e)
        {
            e.printStackTrace();
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaptureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaptureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaptureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaptureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaptureFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tgui.RoundButton btn;
    private tgui.TButton tButton1;
    // End of variables declaration//GEN-END:variables
}
